### ISSUE TITLE
Filtering messes with pagination

### ISSUE THREAD

**Issue by rk222ev** [Armiger/Jarl#33]
When filtering pagination current and page count are being calculated on the full machine list.

The solution is probably to move the filtered list to the datastore and then calculate pagination on that object. The filtered list should really not be held by the machine-list page.

**Comment by mw222rs** [comment]
Yeah It's probably easiest to have a filtered list in the store. Or you can do like I did [here](https://github.com/mw222rs/Suddenly_A_Project/blob/gh-pages/src/components/wrapper.js#L21) just have a variable that's computed.

**Comment by mw222rs** [comment]
Hmm, no it seems to be the machine reducer thats messing things up. When filter changes the offset stuff goes away.

**Comment by rk222ev** [comment]
Fixed that one with: Armiger/LaundroMap-client/pull/36
