### ISSUE TITLE
Link map markers to machine

### ISSUE THREAD

**Issue by rk222ev** [Armiger/Jarl#35]
@mw222rs how are the map marker links coming along? Think you'll be able to do a PR soon?
Would be nice to have it in place so I can complete my presentation.

**Comment by mw222rs** [comment]
Sorry about my tardiness, I'll be traveling all of tomorrow but I'll try to
get the PR in on Saturday.

On Thursday, 26 May 2016, Robin Karlsson <notifications@github.com> wrote:

> @mw222rs <https://github.com/mw222rs> how are the map marker links coming
> along? Think you'll be able to do a PR soon?
> Would be nice to have it in place so I can complete my presentation.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Armiger/Jarl/issues/35>
>


-- 
Med vänliga hälsningar,
Mattias Wikström - mw222rs - WP14
